# Generated by Django 3.1.5 on 2021-07-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0007_blockedstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbluser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
